version: '3'
services:
  web:
    build: .
    container_name: etl_app
    depends_on:
      - db
    environment:
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    networks:
      - etl_network

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    networks:
      - etl_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  etl_network:
    driver: bridge

volumes:
  postgres_data:
